---
# tasks file for Hubs

- name: Create Network Object
  fortios_firewall_address:
    vdom: "{{ vdom }}"
    state: "present"
    firewall_address:
      type: "subnet"
      name: ExampleObject
      color: "3"
      comment: "Test Network Object Creation"
      subnet: "172.16.69.0/24"

- name: Create ExampleObject FW Group
  fortios_firewall_addrgrp:
    vdom: "{{ vdom }}"
    state: "present"
    firewall_addrgrp:
      color: "3"
      comment: "ExampleObject"
      name: "ExampleObjectGroup"
      member: 
        - name: "ExampleObject"

- name: Create IPsec VPN Configuration Phase 1
  fortios_vpn_ipsec_phase1_interface:
    vdom: "{{ vdom }}"
    state: "present"
    vpn_ipsec_phase1_interface: 
      name: "{{ vpnName }}" 
      type: "dynamic"
      interface: "{{ wanIntf }}"
      ip_version: "4"
      ike_version: "2"
      local_gw: "0.0.0.0"
      remote_gw: "0.0.0.0"
      keylife: "86400"
      authmethod: "psk"
      mode: "main"
      peertype: "any"
      default_gw: "0.0.0.0"
      default_gw_priority: "0"
      tunnel_search: "nexthop"
      passive_mode: "disable"
      mode_cfg: "disable"
      unity_support: "enable"
      proposal: "des-md5"
      psksecret: "vpnPassword1!"
      auto_negotiate: "enable"
      keepalive: "10"
      distance: "15"
      priority: "0"
      wizard_type: "custom"
      fragmentation: "enable"
      dpd: "on-idle"
      comments: "VPN test"
      dhgrp: "14"
      signature_hash_alg: "sha1"
      rsa_signature_format: "pkcs1"
      cert_id_validation: "enable"
      nattraversal: "disable"

- name: Create IPsec VPN Configuration Phase 2
  fortios_vpn_ipsec_phase2_interface:
    vdom: "{{ vdom }}"
    state: "present"
    vpn_ipsec_phase2_interface: 
      name: "{{ vpnName }}" 
      phase1name: "{{ vpnName }}"
      dhcp_ipsec: "disable"
      proposal: "des"
      pfs: "enable"
      dhgrp: "14"
      replay: "enable"
      keepalive: "disable"
      auto_negotiate: "disable"
      auto_discovery_forwarder: "phase1"
      auto_discovery_sender: "phase1"
      add_route: "phase1"
      keylifeseconds: "43200"
      keylifekbs: "5210"
      keylife_type: "seconds"
      route_overlap: "use-new"
      encapsulation: "tunnel-mode"
      l2tp: "disable"
      comments: "test Phase II VPN"

- name: Create Generic Firewall Policy
  fortios_firewall_policy:
    vdom: "{{ vdom }}"
    state: "present"
    firewall_policy:
      policyid: "1"
      name: NameofFirewallPolicy
      action: "accept"
      nat: "disable"
      srcintf: 
      - name: "port1"
      dstintf:
      - name: "port2"
      dstaddr: 
      - name: "all"
      srcaddr: 
      - name: "all"
      status: "enable"
      service:
      - name: "ALL"
      schedule: "always"
      inspection_mode: "flow"
      comments: "Basic Firewall Policy Creation with Ansible."

# Next, create firewall policies for the VPN to permit traffic into and out of the tunnel.
# Also, configure BGP for the tunnel.