---
# tasks file for VPN Spokes
- name: Configuring a SW Switch
  fortios_system_switch_interface:
    vdom:  "{{ vdom }}"
    state: "present"
    system_switch_interface:
      name: "Internal"
      type: "switch"
      vdom: "{{ vdom }}"
      member: 
      - interface_name: "port3"
      - interface_name: "port4"
      span: "disable"
    
- name: Create Network Object
  fortios_firewall_address:
    vdom: "{{ vdom }}"
    state: "present"
    firewall_address:
      type: "subnet"
      name: ExampleObject
      interface: "{{ wanIntf }}"
      associated_interface: "{{ wanIntf }}"
      color: "3"
      comment: "Test Network Object Creation"
      subnet: "172.16.69.0/24"
    
- name: Create ExampleObject FW Group
  fortios_firewall_addrgrp:
    vdom: "{{ vdom }}"
    state: "present"
    firewall_addrgrp:
      color: "3"
      comment: "ExampleObject"
      name: "ExampleObjectGroup"
      member: 
        - name: "ExampleObject"


- name: Create Local Address Object
  fortios_firewall_address:
    vdom: "{{ vdom }}"
    state: "present"
    firewall_address:
      type: "subnet"
      name: "Spoke"
      comment: "LAN object"
      subnet: "{{ host_subnet }}"
      color: "3"

- name: Create LDAP Object for AD Login
  fortios_user_ldap:
    vdom: "{{ vdom }}"
    state: "present"
    user_ldap: 
      name: "LDAP" 
      server: "{{ ldapPrimary }}"
      secondary_server: "{{ ldapSecondary }}"
      source_ip: "0.0.0.0"
      cnid: "sAMAccountName"
      dn: "ou=OrganizationUnit,dc=domain,dc=tld"
      type: "regular"
      secure: "ldaps"
      username: "LDAPUser"
      password: "LDAPPassword"
      port: "636"

- name: Create IPsec VPN Configuration Phase 1
  fortios_vpn_ipsec_phase1_interface:
    vdom: "{{ vdom }}"
    state: "present"
    vpn_ipsec_phase1_interface: 
      name: "{{ hostname }}" 
      type: "static"
      interface: "{{ wanIntf }}"
      ip_version: "4"
      ike_version: "2"
      local_gw: "0.0.0.0"
      remote_gw: "{{ vpn_gateway }}"
      backup_gateway: "{{ backup_gateway }}"
      keylife: "86400"
      authmethod: "psk"
      mode: "main"
      peertype: "any"
      default_gw: "0.0.0.0"
      default_gw_priority: "0"
      tunnel_search: "selectors"
      passive_mode: "disable"
      mode_cfg: "disable"
      unity_support: "enable"
      proposal: "des-sha1"
      psksecret: "vpnPassword1!"
      auto_negotiate: "enable"
      keepalive: "10"
      distance: "15"
      priority: "0"
      wizard_type: "custom"
      fragmentation: "enable"
      dpd: "on-idle"
      comments: "VPN"
      dhgrp: "14"
      signature_hash_alg: "sha1"
      rsa_signature_format: "pkcs1"
      cert_id_validation: "enable"

- name: Create IPsec VPN Configuration Phase 2
  fortios_vpn_ipsec_phase2_interface:
    vdom: "{{ vdom }}"
    state: "present"
    vpn_ipsec_phase2_interface: 
      name: "{{ hostname }}" 
      phase1name: "{{ hostname }}"
      dhcp_ipsec: "disable"
      proposal: "des"
      pfs: "enable"
      dhgrp: "14"
      replay: "enable"
      keepalive: "disable"
      auto_negotiate: "disable"
      auto_discovery_forwarder: "phase1"
      auto_discovery_sender: "phase1"
      add_route: "phase1"
      keylifeseconds: "43200"
      keylifekbs: "5210"
      keylife_type: "seconds"
      route_overlap: "use-new"
      encapsulation: "tunnel-mode"
      l2tp: "disable"
      comments: "Phase II"
      protocol: 0

- name: Create Generic Firewall Policy
  fortios_firewall_policy:
    vdom: "{{ vdom }}"
    state: "present"
    firewall_policy:
      policyid: "1"
      name: NameofFirewallPolicy
      action: "accept"
      nat: "disable"
      srcintf: 
      - name: "port1"
      dstintf:
      - name: "port2"
      dstaddr: 
      - name: "all"
      srcaddr: 
      - name: "all"
      status: "enable"
      service:
      - name: "ALL"
      schedule: "always"
      inspection_mode: "flow"
      comments: "Basic Firewall Policy Creation with Ansible."

# Next, create firewall policies for the VPN to permit traffic into and out of the tunnel.
# Also, configure BGP for the tunnel.