---
    #Order
    #1. Create Interfaces
    #2. Create Address Objects
    #3. Create LDAP
    #4. Create VPN
    #5. Cleanup 
    #   (Create Local Admin, disable default)
    #   (Create API Users, add to hosts)
    #6. Tie into FortiManager

- hosts: fortigates
  collections: 
  - fortinet.fortios
  connection: httpapi
  gather_facts: no
  tasks:
  - name: Configuring the Basics
    include_role:
      name: globalSettings

- hosts: spokes
  collections: 
  - fortinet.fortios
  connection: httpapi
  gather_facts: no
  tasks:
  - name: Spoke Configuration
    include_role:
      name: spoke

- hosts: hubs
  collections: 
  - fortinet.fortios
  connection: httpapi
  gather_facts: no
  tasks: 
  - name: Hub Configuration
    include_role:
      name: hub

# - hosts: fortigates
#   collections:
#   - fortinet.fortios
#   connection: httpapi
#   gather_Facts: no
#   tasks:
#   - name: Device hardening
#     include_role:
#       name: hardening