---
all:
  vars:
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    ansible_network_os: fortinet.fortios.fortios
    vdom: "root"
  children:
    fortigates:
      vars: 
        ansible_httpapi_port: 80
        ansible_user: "admin"
        ansible_password: "admin"
      children: 
        hubs:
          children:
            westHubs:
              hosts:
                VPNHubWest:
                  ansible_host: 192.168.0.10
                  hostname: "VPNHubWest"
                  vpnName: "West"
                  wanIntf: port2

            eastHubs:
              hosts:
                PC-VPNHub-East:
                  ansible_host: 192.168.0.11
                  hostname: "VPNHubEast"
                  vpnName: "East"
                  wanIntf: port2

        spokes:
          vars:
            wanIntf: port2
          children:

            westSpokes:
              vars: 
                vpn_gateway: "192.168.0.10"
                backup_gateway: "192.168.0.11"
                ldapPrimary: "192.168.0.1"
                ldapSecondary: "192.168.0.2"

              hosts: 
                SpokeWest:
                  ansible_host: 192.168.0.12
                  hostname: "SpokeWest"
                  host_address: "192.168.1.1/24"
                  host_subnet: "192.168.1.0/24"

            eastSpokes:
              vars:
                vpn_gateway: "192.168.0.11"
                backup_gateway: "192.168.0.10"
                ldapPrimary: "192.168.0.2"
                ldapSecondary: "192.168.0.1"
              hosts:
                SpokeEast:
                  ansible_host: 192.168.0.13
                  hostname: "SpokeEast"
                  host_address: "192.168.2.1/24"
                  host_subnet: "192.168.2.0/24"