---
all:
  vars:
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    ansible_network_os: fortinet.fortios.fortios
    vdom: "root"
  children:
    test:
      vars: 
        ansible_user: "Bradley Rose"
        ansible_password: "J7*bL2f!Om2mlN3F$gJY"
      hosts:
        personal:
          ansible_host: 10.69.10.254
      

    fortigates:
      vars: 
        vdom: "root"
        ansible_httpapi_use_ssl: no
        ansible_httpapi_validate_certs: no
        ansible_httpapi_port: 80
        ansible_user: "admin"
        ansible_password: "admin"
        ansible_network_os: fortinet.fortios.fortios

      children: 
        hubs:
          children:
            westHubs:
              hosts:

                PC-VPNHub-West:
                  ansible_host: 192.168.100.20
                  hostname: "PC-VPNHub-West"
                  vpnName: "PC-West"
                  wanIntf: port2

            eastHubs:
              hosts:
                PC-VPNHub-East:
                  ansible_host: 192.168.100.21
                  hostname: "PC-VPNHub-East"
                  vpnName: "PC-East"
                  wanIntf: port2

        spokes:
          vars:
            wanIntf: port2
          children:

            westSpokes:
              vars: 
                vpn_gateway: "209.171.202.157"
                backup_gateway: "205.193.180.7"
                ldapPrimary: "192.168.177.50"
                ldapSecondary: "10.1.136.42"

              hosts: 
                VPN_Spoke_West:
                  ansible_host: 192.168.100.22
                  hostname: "PC120-SSC"
                  host_address: "10.10.120.1/24"
                  host_subnet: "10.10.120.0/24"

            eastSpokes:
              vars:
                vpn_gateway: "205.193.180.7"
                backup_gateway: "209.171.202.157"
                ldapPrimary: "10.1.136.42"
                ldapSecondary: "192.168.177.50"
              hosts:
                VPN_Spoke_East:
                  ansible_host: 192.168.100.23
                  hostname: "PC110-SSC"
                  host_address: "10.10.110.1/24"
                  host_subnet: "10.10.110.0/24"