---
fortigates:
  vars: 
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_network_os: fortinet.fortios.fortios

  children: 
    hubs:
      children:
        westHubs:
          hosts:

            PC-VPNHub-West:
              ansible_host: 192.168.100.20
              hostname: "PC-VPNHub-West"
              vpnName: "PC-West"
              #access_token: 5fNc8nck41pNq7gcm01yzQ065d6Gy8
              wanIntf: "mgmt2"

        eastHubs:
          hosts:
            PC-VPNHub-East:
              ansible_host: 192.168.100.21
              hostname: "PC-VPNHub-East"
              vpnName: "PC-East"
              #access_token: 5fNc8nck41pNq7gcm01yzQ065d6Gy8
              wanIntf: "port10"

    spokes:
      children:

        westSpokes:
          vars: 
            vpn_gateway: "209.171.202.157"
            backup_gateway: "205.193.180.7"
          hosts: 
            PC120-SSC:
              ansible_host: 192.168.100.22
              #access_token: 66rcdpHksj7g9hgpbnswbQtqzt4k8t
              hostname: "PC120-SSC"

        eastSpokes:
          vars:
            vpn_gateway: "205.193.180.7"
            backup_gateway: "209.171.202.157"
          hosts:
            VPN_Spoke_East:
              ansible_host: 192.168.100.23
              #access_token: bpfh8zr0bbdqjn5qrgH7ctkh50Hs9q
              hostname: "PC110-SSC"