---
# tasks file for pre_check
- name: Create IPsec VPN Configuration Phase 1
  fortios_vpn_ipsec_phase1_interface:
    vdom: "{{ vdom }}"
    state: "present"
    access_token: "{{ access_token }}"
    vpn_ipsec_phase1_interface: 
      name: "{{ vpnName }}" 
      type: "dynamic"
      interface: "mgmt2"
      ip_version: "4"
      ike_version: "2"
      local_gw: "0.0.0.0"
      remote_gw: "0.0.0.0"
      keylife: "86400"
      authmethod: "psk"
      mode: "main"
      peertype: "any"
      default_gw: "0.0.0.0"
      default_gw_priority: "0"
      tunnel_search: "nexthop"
      passive_mode: "disable"
      mode_cfg: "disable"
      unity_support: "enable"
      proposal: "chacha20poly1305-prfsha384"
      psksecret: "3ZVPN@ccess"
      auto_negotiate: "enable"
      keepalive: "10"
      distance: "15"
      priority: "0"
      wizard_type: "custom"
      fragmentation: "enable"
      dpd: "on-idle"
      comments: "VPN Tunnel to Remote Parks Canada sites."
      dhgrp: "20"
      signature_hash_alg: "sha2-512, sha2-384 sha2-256"
      rsa_signature_format: "pkcs1"
      cert_id_validation: "enable"
      nattraversal: "enable"

- name: Create IPsec VPN Configuration Phase 2
  fortios_vpn_ipsec_phase2_interface:
    vdom: "{{ vdom }}"
    state: "present"
    access_token: "{{ access_token }}"
    vpn_ipsec_phase2_interface: 
      name: "{{ vpnName }}" 
      phase1name: "{{ vpnName }}"
      dhcp_ipsec: "disable"
      proposal: "chacha20poly1305"
      pfs: "enable"
      dhgrp: "20"
      replay: "enable"
      keepalive: "disable"
      auto_negotiate: "disable"
      auto_discovery_forwarder: "phase1"
      auto_discovery_sender: "phase1"
      add_route: "phase1"
      keylifeseconds: "43200"
      keylifekbs: "5210"
      keylife_type: "seconds"
      route_overlap: "use-new"
      encapsulation: "tunnel-mode"
      l2tp: "disable"
      comments: "Phase II for PC VPN"
      protocol: 0